[build]
    functions = "functions"
    publish = "public"
[dev]
functions = "functions"
cmd = "pip install -r requirements.txt && netlify-lambda build functions"

[[plugins]]
package = "netlify-lambda"
  