name: Add FFmpeg to Repository

on:
  workflow_dispatch: # Allows manual triggering of the workflow.

jobs:
  add_ffmpeg:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Download FFmpeg for Linux
    - name: Download FFmpeg
      run: |
        mkdir -p ffmpeg
        curl -L -o ffmpeg/ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
        cd ffmpeg
        tar -xf ffmpeg.tar.xz --strip-components=1
        rm ffmpeg.tar.xz # Remove the archive to save space

    # Step 3: Commit and push FFmpeg folder
    - name: Commit and push FFmpeg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ffmpeg/
        git commit -m "Add FFmpeg binaries for Linux"
        git push
