name: Install FFmpeg and Push to Repository

on:
  workflow_dispatch: # Manual trigger

jobs:
  install_ffmpeg:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install FFmpeg
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    # Step 3: Copy FFmpeg binary to the repository
    - name: Copy FFmpeg to repo folder
      run: |
        mkdir -p ffmpeg
        cp $(which ffmpeg) ffmpeg/ffmpeg

    # Step 4: Commit and push FFmpeg folder
    - name: Commit and push FFmpeg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ffmpeg/
        git commit -m "Add FFmpeg binaries installed via apt-get"
        git push
